
[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/apcera/termtables"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
